#!/bin/sh

set -e -x
# export PATH="${PWD}/toolchain/gcc/bin:${PATH}"
# rm -rf out
# mkdir -p out

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-"
# make O=out $xxx a02_defconfig
# make O=out $xxx -j"$(nproc --all)" 2>&1 | tee build.log
make O=out $xxx -j8 2>&1 | tee build.log
